// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SubscribeRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type Notice struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notice) Reset()         { *m = Notice{} }
func (m *Notice) String() string { return proto.CompactTextString(m) }
func (*Notice) ProtoMessage()    {}
func (*Notice) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *Notice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notice.Unmarshal(m, b)
}
func (m *Notice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notice.Marshal(b, m, deterministic)
}
func (m *Notice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notice.Merge(m, src)
}
func (m *Notice) XXX_Size() int {
	return xxx_messageInfo_Notice.Size(m)
}
func (m *Notice) XXX_DiscardUnknown() {
	xxx_messageInfo_Notice.DiscardUnknown(m)
}

var xxx_messageInfo_Notice proto.InternalMessageInfo

func (m *Notice) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*SubscribeRequest)(nil), "helloworld.SubscribeRequest")
	proto.RegisterType((*Notice)(nil), "helloworld.Notice")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x1b, 0x90, 0xb6, 0x0e, 0x42, 0xcb, 0x1c, 0x64, 0x59, 0x3d, 0xc8, 0x1c, 0xc4, 0x53,
	0x28, 0x7a, 0xf7, 0xd0, 0x4b, 0x3d, 0x49, 0x69, 0x0f, 0x9e, 0x77, 0xb7, 0x43, 0x0d, 0x64, 0x9b,
	0x98, 0xa4, 0x68, 0xfe, 0x86, 0xbf, 0x58, 0x36, 0xee, 0xd6, 0x20, 0x7a, 0x9b, 0x97, 0xf9, 0x32,
	0xf3, 0xe6, 0xc1, 0xfc, 0x95, 0xb5, 0x36, 0xef, 0xc6, 0xe9, 0x9d, 0xb4, 0xce, 0x04, 0x83, 0xf0,
	0xf3, 0x42, 0x04, 0x17, 0x4f, 0x9d, 0xda, 0xf0, 0xdb, 0x91, 0x7d, 0x40, 0x84, 0xb3, 0x43, 0xd5,
	0x72, 0x21, 0x6e, 0xc4, 0xdd, 0xf9, 0x26, 0xd5, 0x74, 0x0b, 0xd0, 0x33, 0x56, 0x47, 0x2c, 0x60,
	0xd2, 0xb2, 0xf7, 0xd5, 0x7e, 0x80, 0x06, 0x49, 0x12, 0xe6, 0xdb, 0x63, 0xed, 0x1b, 0xa7, 0x6a,
	0x1e, 0xe6, 0x95, 0x30, 0x55, 0x3b, 0x3e, 0x04, 0x15, 0x62, 0x8f, 0x9f, 0x34, 0x11, 0x8c, 0x9f,
	0x4d, 0x50, 0x0d, 0xff, 0x3f, 0xf3, 0xfe, 0x53, 0xc0, 0x64, 0xe5, 0x98, 0x03, 0x3b, 0x7c, 0x84,
	0xe9, 0xb6, 0x8a, 0xc9, 0x0a, 0x16, 0x32, 0x3b, 0x2b, 0xbf, 0xa0, 0xbc, 0xfc, 0xa3, 0x63, 0x75,
	0xa4, 0x11, 0xae, 0x60, 0x76, 0xf2, 0xd7, 0x2f, 0xbe, 0xce, 0xe1, 0xdf, 0xe6, 0x4b, 0xcc, 0xbb,
	0xdf, 0x3f, 0x68, 0xb4, 0x10, 0xcb, 0x05, 0x5c, 0x29, 0x23, 0xf7, 0xce, 0x36, 0x92, 0x3f, 0xaa,
	0xd6, 0x6a, 0xf6, 0x19, 0xb9, 0x9c, 0xa5, 0xad, 0x2f, 0x5d, 0xbd, 0xee, 0x02, 0x5f, 0x8b, 0x7a,
	0x9c, 0x92, 0x7f, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x55, 0x28, 0x96, 0x3b, 0x8d, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Subscribe a stream of notice
	SubscribeNotice(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Greeter_SubscribeNoticeClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SubscribeNotice(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Greeter_SubscribeNoticeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/helloworld.Greeter/SubscribeNotice", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSubscribeNoticeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SubscribeNoticeClient interface {
	Recv() (*Notice, error)
	grpc.ClientStream
}

type greeterSubscribeNoticeClient struct {
	grpc.ClientStream
}

func (x *greeterSubscribeNoticeClient) Recv() (*Notice, error) {
	m := new(Notice)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Subscribe a stream of notice
	SubscribeNotice(*SubscribeRequest, Greeter_SubscribeNoticeServer) error
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedGreeterServer) SubscribeNotice(req *SubscribeRequest, srv Greeter_SubscribeNoticeServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeNotice not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SubscribeNotice_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SubscribeNotice(m, &greeterSubscribeNoticeServer{stream})
}

type Greeter_SubscribeNoticeServer interface {
	Send(*Notice) error
	grpc.ServerStream
}

type greeterSubscribeNoticeServer struct {
	grpc.ServerStream
}

func (x *greeterSubscribeNoticeServer) Send(m *Notice) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeNotice",
			Handler:       _Greeter_SubscribeNotice_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}
